### ISSUE TITLE
Support for Android Gradle plugin 7.0.0 and Java11

### ISSUE THREAD

**Issue by davidattias** [bitrise-steplib/steps-install-missing-android-tools#65]
I've upgraded my IDE to Android Studio 4.2 Preview (Artic Fox 2020.3.1) because my project is using the new Compose framework.

This latest version require now Android Gradle plugin 7.0.0 alpha1 which is using Java11. So I've upgraded my plugin to this version.

When building my project using Bitrise, it fails in the step `install-missing-android-tools` with the following stack:

```
Failed to ensure android components, error: output: FAILURE: Build failed with an exception.
* Where:
Build file '/bitrise/src/app/build.gradle' line: 2
* What went wrong:
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.
* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Exception is:
org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'com.android.application']
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.exceptionOccurred(DefaultPluginRequestApplicator.java:198)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:180)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.lambda$applyPlugins$1(DefaultPluginRequestApplicator.java:125)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:125)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:121)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:117)
```

Do you plan to support this new version ?

Thanks

**Comment by chaitanyatanna-bitrise** [comment]
Hi @davidattias 
Thank you for reaching out to Bitrise Support.
This documentation would help you out with upgrading to the new version of Java - https://devcenter.bitrise.io/infrastructure/virtual-machines/#managing-java-versions

Thanks
Chaitanya

**Comment by davidattias** [comment]
Fixed my issue! Thanks!

**Comment by chaitanyatanna-bitrise** [comment]
Awesome @davidattias 

Chaitanya
